Pagination
NYPL-Simplified/webpub-viewer pull request #2
Opened 2017-01-31 19:02 UTC by aslagle

2017-01-31 23:06 UTC, winniequinn requested changes

2017-01-31 23:06 UTC, winniequinn commented on src/ColumnsPaginator.ts
> +        let position = -(this.iframe.contentDocument.body.style.left || "0px").slice(0, -2);
Many of these variables could be declared `const` instead.

2017-01-31 23:06 UTC, winniequinn commented on src/ColumnsPaginator.ts
> +        let width = this.iframe.contentDocument.body.offsetWidth;
Perhaps we can factor out `position` and `width` to their own functions with more descriptive names to avoid code duplication?

2017-01-31 23:06 UTC, winniequinn commented on src/ColumnsPaginator.ts
> +    public goToPosition(position: number) {
We should document that `position` must be in range [0..1].

2017-01-31 23:06 UTC, winniequinn commented on src/IFrameNavigator.ts
> -        if (!iframe || !nextLink || !previousLink || !startLink || !contentsLink || !navigation ||
It might be better to have a helper function that wraps `querySelector` which returns a non-null value or throws an exception if there's an internal inconsistency.

2017-01-31 23:06 UTC, winniequinn commented on src/IFrameNavigator.ts
> +            !(nextChapterLink instanceof HTMLAnchorElement) ||
We could handle these with `as` where they're first assigned.

2017-01-31 23:06 UTC, winniequinn commented on src/IFrameNavigator.ts
> +                window.location.hostname == link.hostname
===

2017-01-31 23:06 UTC, winniequinn commented on src/IFrameNavigator.ts
> +        this.loading.style.display = "block";
It would be nice if we displayed this after N milliseconds to avoid it flashing on every load.

2017-02-01 17:39 UTC, aslagle commented
@winniequinn I addressed all your comments

2017-02-01 22:16 UTC, winniequinn approved these changes

2017-02-01 22:16 UTC, merged