Implemented table of contents using TOC from manifest instead of contents link
NYPL-Simplified/webpub-viewer pull request #3
Opened 2017-02-01 22:17 UTC by aslagle

2017-02-01 22:36 UTC, winniequinn requested changes
As discussed, I think it would be better if the TOC were full-screen. It would make it easier to have UI for closing the TOC, would make dealing with accessibility issues somewhat easier, and would allow for a less cramped view on mobile. Our current apps for Android and iOS are a good source of inspiration here.

2017-02-01 22:36 UTC, winniequinn commented on src/IFrameNavigator.ts
> +        if (display && display === "none") {
We can just do `display === "none"`.

2017-02-02 15:33 UTC, aslagle commented on src/IFrameNavigator.ts
> +        if (display && display === "none") {
fixed

2017-02-02 15:34 UTC, aslagle commented
I changed the example in this repo to have a full-screen TOC, and it's scrollable now.

2017-02-06 18:57 UTC, winniequinn approved these changes

2017-02-06 18:58 UTC, merged